app/routes/cart_routes.py
from flask import Blueprint, Response, flash, redirect, url_for, request
from werkzeug.exceptions import HTTPException

from app.models import Restaurant, MenuItem
from app.services.cart_service import (
    add_item_to_cart,
    increment_item_quantity_in_cart,
    decrement_item_quantity_in_cart,
)

cart_routes = Blueprint("cart", __name__)


@cart_routes.route(
    "/search/<int:restaurant_id>/cart/add/<int:item_id>", methods=["GET"]
)
def add_to_cart(restaurant_id: int, item_id: int) -> Response:
    try:
        restaurant = Restaurant.query.get_or_404(restaurant_id)
        item = MenuItem.query.get_or_404(item_id)
    except HTTPException:
        flash("The requested restaurant or item does not exist.", "danger")

        return redirect(url_for("index.index"))

    add_item_to_cart(restaurant=restaurant, item=item)

    flash("Item added to cart.", "success")

    return redirect(request.referrer or url_for("index.index"))


@cart_routes.route(
    "/search/<int:restaurant_id>/cart/<int:cart_id>/increment/<int:item_id>",
    methods=["GET"],
)
def increment_item_quantity(restaurant_id: int, cart_id: int, item_id: int) -> Response:
    try:
        restaurant = Restaurant.query.get_or_404(restaurant_id)
        item = MenuItem.query.get_or_404(item_id)
    except HTTPException:
        flash("The requested restaurant or item does not exist.", "danger")

        return redirect(url_for("index.index"))

    return increment_item_quantity_in_cart(
        restaurant=restaurant, item=item, cart_id=cart_id
    )


@cart_routes.route(
    "/search/<int:restaurant_id>/cart/<int:cart_id>/decrement/<int:item_id>",
    methods=["GET"],
)
def decrement_item_quantity(restaurant_id: int, cart_id: int, item_id: int) -> Response:
    try:
        restaurant = Restaurant.query.get_or_404(restaurant_id)
        item = MenuItem.query.get_or_404(item_id)
    except HTTPException:
        flash("The requested restaurant or item does not exist.", "danger")

        return redirect(url_for("index.index"))

    return decrement_item_quantity_in_cart(
        restaurant=restaurant, item=item, cart_id=cart_id
    )

app/templates/components/search/restaurant_header.html
<a class="my-3" href="{{ attributes.results_url }}">
  <i class="fa-solid fa-chevron-left me-2"></i>Back to search results
</a>

<img src="{{ url_for('static', filename="images/search-heading-carousel-01.jpg") }}" class="d-block w-100 rounded"
     alt="Search heading image 1"/>

<section class="restaurant-header d-flex justify-content-between my-5">
  <div class="d-flex gap-4">
    <img class="header-image rounded" src="{{ url_for('static', filename="images/search-heading-carousel-02.jpg") }}" alt="Restaurant Image"/>
    <div>
      <h1 class="fs-4 mb-1">{{ attributes.restaurant.name }}</h1>
      <p class="mb-0">
        <i class="fa-solid fa-star"></i>
        <i class="fa-solid fa-star"></i>
        <i class="fa-solid fa-star"></i>
        <i class="fa-solid fa-star"></i>
        <i class="fa-regular fa-star-half"></i>
      </p>
      <small class="text-body-secondary">4k Ratings</small>
    </div>
  </div>

  <p class="text-muted">
    {{ attributes.restaurant.description }}
  </p>
</section>

app/templates/components/search/restaurant_menu.html
<div class="row mb-5" data-masonry='{"percentPosition": true }'>
  {% for item in attributes.menu_items %}
    <div class="col-4 mb-3">
      <div class="card">
        {% if item.image and item.image.startswith('https') %}
          <img
              src="{{ item.image }}"
              alt="{{ item.item_name }}"
              class="card-img-top"
          />
        {% elif item.image %}
          <img
              src="{{ url_for('static', filename="uploads/images/" + item.image) }}"
              alt="{{ item.item_name }}"
              class="card-img-top"
          />
        {% else %}
          <img
              src="{{ url_for('static', filename="images/no-image.jpg") }}"
              class="img-fluid rounded-start w-100"
              alt="No image available"
          />
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ item.name }}</h5>
          <p class="card-text">{{ item.description }}</p>
          <div class="d-flex align-items-center justify-content-end mt-4">
            <span class="fs-3 text-success me-3">{{ "%.2f" % item.price }}€</span>
            <a href="{{ url_for('cart.add_to_cart', restaurant_id=attributes.restaurant.id, item_id=item.id) }}"
               class="btn btn-dark">
              <i class="fa-solid fa-cart-shopping me-2"></i>Add to cart
            </a>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div class="alert alert-dark">
      The restaurant does not have any items in the menu for the time being...
    </div>
  {% endfor %}
</div>

app/templates/components/search/restaurants_list_component.html
{% macro restaurant_card(restaurant) %}
  <div class="row g-0">
    <div class="col-md-4">
      {% if restaurant.image and restaurant.image.startswith('https') %}
        <img
            src="{{ restaurant.image }}"
            class="img-fluid rounded-start"
            alt="{{ restaurant.name }}"
        />
      {% elif restaurant.image %}
        <img
            src="{{ url_for('static', filename="uploads/images/" + restaurant.image) }}"
            class="img-fluid rounded-start"
            alt="{{ restaurant.name }}"
        />
      {% else %}
        <img
            src="{{ url_for('static', filename="images/no-image.jpg") }}"
            class="img-fluid rounded-start w-100"
            alt="No image available"
        />
      {% endif %}
    </div>
    <div class="col-md-8">
      <div class="d-flex flex-column justify-content-start card-body h-100">
        <h5 class="card-title">{{ restaurant.name }}</h5>
        <p class="card-text">{{ restaurant.description }}</p>
        {% if restaurant.is_available() %}
          <p class="d-flex align-items-center justify-content-start gap-1 text-success">
            <i class="fa-regular fa-clock"></i>Currently open
          </p>
        {% else %}
          <p class="d-flex align-items-center justify-content-start gap-1 text-danger">
            <i class="fa-regular fa-clock"></i>Closed
          </p>
        {% endif %}
        <p class="d-flex align-items-center align-self-end gap-1 card-text mt-auto">
          <small class="me-1 text-body-secondary">
            ({{ restaurant.get_average_rating() }})
          </small>
          {% set rounded_rating = restaurant.get_average_rating() | round | int %}
          {% for star in range(rounded_rating) %}
            <i class="fa-solid fa-star"></i>
          {% endfor %}
          {% for star in range(5 - rounded_rating) %}
            <i class="fa-regular fa-star"></i>
          {% endfor %}
          <small class="ms-1 text-body-secondary">
            {{ restaurant.get_ratings_count() }} Rating(s)
          </small>
        </p>
      </div>
    </div>
  </div>
{% endmacro %}

<section class="d-flex flex-column align-items-stretch gap-3 my-5">
  {% for restaurant in attributes.restaurants %}
    {% if restaurant.is_available() %}
      <a href="{{ url_for('index.restaurant_page', restaurant_id=restaurant.id) }}"
         class="card border-bottom text-decoration-none">
        {{ restaurant_card(restaurant) }}
      </a>
    {% else %}
      <div class="card border-bottom bg-secondary-subtle text-decoration-none">
        {{ restaurant_card(restaurant) }}
      </div>
    {% endif %}
    {% if not loop.last %}
      <hr/>
    {% endif %}
  {% else %}
    <div class="alert alert-dark">
      No restaurants were found for your search criteria.
    </div>
  {% endfor %}
</section>

app/templates/components/search/search_header.html
<section id="search-header" class="search-header d-flex flex-column align-items-stretch my-4">
  <div class="border-bottom pb-3">
    <h1 class="d-flex align-items-center gap-2 fs-4">Top Results found for your search criteria...</h1>
    <span class="text-secondary">{{ attributes.restaurants_count }} restaurants</span>
  </div>

  <div class="d-flex justify-content-between align-items-center mt-3">
    <div class="d-flex flex-wrap gap-1">
      {% for term in attributes.terms_list %}
        <span class="badge text-bg-dark">
          {{ term.label }}
          <a class="ms-2 text-white" href="{{ term.link }}"><i class="fa-solid fa-xmark"></i></a>
        </span>
      {% endfor %}
    </div>

    <form class="sort-results-select-box" method="GET">
      <select class="form-select" name="sort_by">
        <option value="none">Sort Results By</option>
        {% for query_sort in attributes.QuerySort %}
          <option value="{{ query_sort.name }}">{{ query_sort.value }}</option>
        {% endfor %}
      </select>
    </form>
  </div>
</section>

<script>
  (function () {
    const selectElement = document.querySelector('#search-header .sort-results-select-box select');

    if (!selectElement) {
      throw new Error("Select element for sorting options is not found");
    }

    const urlParams = new URLSearchParams(window.location.search);
    const sortByValue = urlParams.get('sort_by');

    if (sortByValue) {
      selectElement.value = sortByValue;
    }

    selectElement.addEventListener('change', (e) => {
      const newSortValue = e.target.value;
      const updatedParams = new URLSearchParams(window.location.search);

      if (newSortValue === 'none') updatedParams.delete('sort_by');
      else updatedParams.set('sort_by', newSortValue);

      window.location.search = updatedParams.toString();
    });
  })();
</script>

app/templates/components/search/search_heading_carousel.html
<div id="search-heading-carousel" class="carousel slide rounded overflow-hidden">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#search-heading-carousel" data-bs-slide-to="0" class="active"></button>
    <button type="button" data-bs-target="#search-heading-carousel" data-bs-slide-to="1"></button>
    <button type="button" data-bs-target="#search-heading-carousel" data-bs-slide-to="2"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ url_for('static', filename="images/search-heading-carousel-01.jpg") }}" class="d-block w-100" alt="Search heading image 1">
    </div>
    <div class="carousel-item">
      <img src="{{ url_for('static', filename="images/search-heading-carousel-02.jpg") }}" class="d-block w-100" alt="Search heading image 2">
    </div>
    <div class="carousel-item">
      <img src="{{ url_for('static', filename="images/search-heading-carousel-03.jpg") }}" class="d-block w-100" alt="Search heading image 3">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#search-heading-carousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#search-heading-carousel" data-bs-slide="next">
    <span class="carousel-control-next-icon"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>