app/models/Menu.py
from app import db


class Menu(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    restaurant_id = db.Column(
        db.Integer, db.ForeignKey("restaurant.id"), unique=True, nullable=False
    )

    # Relationships
    restaurant = db.relationship("Restaurant", back_populates="menu", uselist=False)
    items = db.relationship(
        "MenuItem", back_populates="menu", lazy="dynamic", cascade="all, delete-orphan"
    )

app/routes/admin_routes.py
from flask import Blueprint, Response, redirect, url_for, flash, abort
from flask_login import login_required, current_user

from app import db
from app.components.admin.menu.add_menu_item_component import add_menu_item_component
from app.components.admin.menu.edit_menu_item_component import edit_menu_item_component
from app.components.admin.edit_settings_component import edit_settings_component
from app.components.admin.delivery_radius.get_delivery_radius_component import (
    get_delivery_radius_component,
)
from app.components.admin.menu.menu_overview_component import menu_overview_component
from app.components.admin.menu.menu_page_navigation_component import (
    menu_page_navigation_component,
)
from app.components.admin.orders_table_component import orders_table_component
from app.components.admin.delivery_radius.set_delivery_radius_component import (
    set_delivery_radius_component,
)
from app.components.admin.set_opening_hours_component import set_opening_hours_component
from app.enum.Layout import Layout
from app.models.PostalCodeRestaurant import PostalCodeRestaurant
from app.services.menu_service import delete_item
from app.services.aside_component_service import get_aside_component_for_admin_board
from app.services.component_service import render_page, build_components
from app.services.restaurants_service import display_warning

admin_routes = Blueprint("admin", __name__)


@admin_routes.route("/")
@admin_routes.route("/orders")
@login_required
def index() -> Response:
    display_warning()

    components = build_components(
        main_components=[lambda: orders_table_component(current_user.restaurant)],
        aside_components=[get_aside_component_for_admin_board],
    )

    return render_page(Layout.SPLIT, "Admin", components)


@admin_routes.route("/menu", methods=["GET", "POST"])
@login_required
def menu_overview() -> Response:
    components = build_components(
        main_components=[menu_page_navigation_component, menu_overview_component],
        aside_components=[get_aside_component_for_admin_board],
    )

    return render_page(Layout.SPLIT, "Menu", components)


@admin_routes.route("/menu/add", methods=["GET", "POST"])
@login_required
def add_menu_item() -> Response:
    components = build_components(
        main_components=[menu_page_navigation_component, add_menu_item_component],
        aside_components=[get_aside_component_for_admin_board],
    )

    return render_page(Layout.SPLIT, "Menu - Add Item", components)


@admin_routes.route("/menu/<int:item_id>/edit", methods=["GET", "POST"])
@login_required
def edit_menu_item(item_id: int) -> Response:
    components = build_components(
        main_components=[
            menu_page_navigation_component,
            lambda: edit_menu_item_component(item_id),
        ],
        aside_components=[get_aside_component_for_admin_board],
    )

    return render_page(Layout.SPLIT, "Menu - Edit Item", components)


@admin_routes.route("/menu/<int:item_id>/delete", methods=["GET"])
@login_required
def delete_menu_item(item_id: int) -> Response:
    delete_item(item_id)

    return redirect(url_for("admin.menu_overview"))


@admin_routes.route("/opening-hours", methods=["GET", "POST"])
@login_required
def opening_hours() -> Response:
    components = build_components(
        main_components=[set_opening_hours_component],
        aside_components=[get_aside_component_for_admin_board],
    )

    return render_page(Layout.SPLIT, "Opening Hours", components)


@admin_routes.route("/delivery_radius", methods=["GET", "POST"])
@login_required
def delivery_radius() -> Response:
    components = build_components(
        main_components=[set_delivery_radius_component, get_delivery_radius_component],
        aside_components=[get_aside_component_for_admin_board],
    )

    return render_page(Layout.SPLIT, "Delivery Radius", components)


@admin_routes.route(
    "/delivery_radius/<int:postal_code_restaurant_id>/delete", methods=["GET"]
)
@login_required
def delete_delivery_radius(postal_code_restaurant_id: int) -> Response:
    postal_code = PostalCodeRestaurant.query.get_or_404(postal_code_restaurant_id)

    if postal_code.restaurant != current_user.restaurant:
        abort(403)

    db.session.delete(postal_code)
    db.session.commit()

    flash("Postal code removed successfully.", "success")

    return redirect(url_for("admin.delivery_radius"))


@admin_routes.route("/settings", methods=["GET", "POST"])
@login_required
def settings() -> Response:
    components = build_components(
        main_components=[edit_settings_component],
        aside_components=[get_aside_component_for_admin_board],
    )

    return render_page(Layout.SPLIT, "Settings", components)

app/templates/components/admin/menu/add_menu_item.html
<div class="card">
  <form method="POST" class="card-body" enctype="multipart/form-data">
    {{ attributes.menu_item_form.hidden_tag() }}

    <div class="mb-3">
      {{ attributes.menu_item_form.file.label(class="form-label", for="file") }}
      {{ attributes.menu_item_form.file(id="file", class="form-control") }}
    </div>
    <div class="mb-3">
      {{ attributes.menu_item_form.item_name.label(class="form-label", for="item_name") }}
      {{ attributes.menu_item_form.item_name(id="item_name", class="form-control") }}
    </div>
    <div class="mb-3">
      {{ attributes.menu_item_form.price.label(class="form-label", for="price") }}
      {{ attributes.menu_item_form.price(id="price", class="form-control") }}
    </div>
    <div class="mb-3">
      {{ attributes.menu_item_form.description.label(class="form-label", for="description") }}
      {{ attributes.menu_item_form.description(id="description", class="form-control") }}
    </div>

    <div class="d-grid">
      <button class="btn btn-dark"><i class="fa-solid fa-floppy-disk me-2"></i>Save</button>
    </div>
  </form>
</div>

app/templates/components/admin/menu/edit_menu_item.html
<h1 class="mb-3">Editing Menu Item: {{ attributes.item_name }}</h1>

<div class="card">
  <form method="POST" class="card-body" enctype="multipart/form-data">
    {{ attributes.menu_item_form.hidden_tag() }}

    <div class="mb-3">
      {{ attributes.menu_item_form.file.label(class="form-label", for="file") }}
      {{ attributes.menu_item_form.file(id="file", class="form-control") }}
    </div>
    <div class="mb-3">
      {{ attributes.menu_item_form.item_name.label(class="form-label", for="item_name") }}
      {{ attributes.menu_item_form.item_name(id="item_name", class="form-control") }}
    </div>
    <div class="mb-3">
      {{ attributes.menu_item_form.price.label(class="form-label", for="price") }}
      {{ attributes.menu_item_form.price(id="price", class="form-control") }}
    </div>
    <div class="mb-3">
      {{ attributes.menu_item_form.description.label(class="form-label", for="description") }}
      {{ attributes.menu_item_form.description(id="description", class="form-control") }}
    </div>

    <div class="d-grid">
      <button class="btn btn-dark"><i class="fa-solid fa-floppy-disk me-2"></i>Save</button>
    </div>
  </form>
</div>

app/templates/components/admin/menu/menu_overview_component.html
<div class="row" data-masonry='{"percentPosition": true }'>
  {% for item in attributes.menu_items %}
    <div class="col-4 mb-3">
      <div class="card">
        {% if item.image and item.image.startswith('https') %}
          <img
              src="{{ item.image }}"
              alt="{{ item.name }}"
              class="card-img-top"
          />
        {% elif item.image %}
          <img
              src="{{ url_for('static', filename="uploads/images/" + item.image) }}"
              alt="{{ item.name }}"
              class="card-img-top"
          />
        {% else %}
          <img
              src="{{ url_for('static', filename="images/no-image.jpg") }}"
              class="img-fluid rounded-start w-100"
              alt="No image available"
          />
        {% endif %}
        <div class="card-body">
          <div class="d-flex align-items-baseline justify-content-between text-center">
            <h5 class="card-title">{{ item.name }}</h5>
            <small class="fs-5 text-success">{{ "%.2f" % item.price }}€</small>
          </div>
          <p class="card-text">{{ item.description }}</p>
          <a href="{{ url_for('admin.edit_menu_item', item_id=item.id) }}" class="btn btn-dark"><i
              class="fa-solid fa-pen-to-square me-2"></i>Edit Item</a>
          <a href="{{ url_for('admin.delete_menu_item', item_id=item.id) }}" class="btn btn-danger"><i
              class="fa-solid fa-trash me-2"></i>Delete Item</a>
        </div>
      </div>
    </div>
  {% else %}
    <div class="alert alert-secondary">
      No items were yet added to the menu add one
      <a class="link-secondary" href="{{ url_for('admin.add_menu_item') }}">here</a>.
    </div>
  {% endfor %}
</div>

app/templates/components/admin/menu/menu_page_navigation.html
<ul class="nav nav-pills mb-3">
  {% for link in attributes.links %}
    <li class="nav-item">
      <a class="nav-link {{ 'active' if link.is_active }}" href="{{ link.href }}">
        <i class="{{ link.icon }}"></i>{{ link.text }}
      </a>
    </li>
  {% endfor %}
</ul>