app/models/Cart.py
from app import db


class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    note = db.Column(db.Text, nullable=True)
    customer_id = db.Column(db.Integer, db.ForeignKey("customer.id"), nullable=False)
    restaurant_id = db.Column(
        db.Integer, db.ForeignKey("restaurant.id"), nullable=False
    )

    # Relationship
    customer = db.relationship("Customer", back_populates="carts", uselist=False)
    restaurant = db.relationship("Restaurant", back_populates="carts", uselist=False)
    items = db.relationship(
        "CartItem", back_populates="cart", cascade="all, delete-orphan"
    )

app/routes/cart_routes.py
from flask import Blueprint, Response, flash, redirect, url_for, request
from werkzeug.exceptions import HTTPException

from app.models import Restaurant, MenuItem
from app.services.cart_service import (
    add_item_to_cart,
    increment_item_quantity_in_cart,
    decrement_item_quantity_in_cart,
)

cart_routes = Blueprint("cart", __name__)


@cart_routes.route(
    "/search/<int:restaurant_id>/cart/add/<int:item_id>", methods=["GET"]
)
def add_to_cart(restaurant_id: int, item_id: int) -> Response:
    try:
        restaurant = Restaurant.query.get_or_404(restaurant_id)
        item = MenuItem.query.get_or_404(item_id)
    except HTTPException:
        flash("The requested restaurant or item does not exist.", "danger")

        return redirect(url_for("index.index"))

    add_item_to_cart(restaurant=restaurant, item=item)

    flash("Item added to cart.", "success")

    return redirect(request.referrer or url_for("index.index"))


@cart_routes.route(
    "/search/<int:restaurant_id>/cart/<int:cart_id>/increment/<int:item_id>",
    methods=["GET"],
)
def increment_item_quantity(restaurant_id: int, cart_id: int, item_id: int) -> Response:
    try:
        restaurant = Restaurant.query.get_or_404(restaurant_id)
        item = MenuItem.query.get_or_404(item_id)
    except HTTPException:
        flash("The requested restaurant or item does not exist.", "danger")

        return redirect(url_for("index.index"))

    return increment_item_quantity_in_cart(
        restaurant=restaurant, item=item, cart_id=cart_id
    )


@cart_routes.route(
    "/search/<int:restaurant_id>/cart/<int:cart_id>/decrement/<int:item_id>",
    methods=["GET"],
)
def decrement_item_quantity(restaurant_id: int, cart_id: int, item_id: int) -> Response:
    try:
        restaurant = Restaurant.query.get_or_404(restaurant_id)
        item = MenuItem.query.get_or_404(item_id)
    except HTTPException:
        flash("The requested restaurant or item does not exist.", "danger")

        return redirect(url_for("index.index"))

    return decrement_item_quantity_in_cart(
        restaurant=restaurant, item=item, cart_id=cart_id
    )

app/templates/components/cart/cart.html
<section class="cart h-100 d-flex flex-column align-items-stretch justify-content-between">
    <div class="cart-start">
        <h2 class="text-uppercase mt-3">
            Cart
        </h2>

        <ul class="list-group list-group-flush">
            {% for cart_item in attributes.cart_items %}
                <li class="list-group-item px-0 d-flex justify-content-between align-items-center">
                    <div class="flex-1 d-flex flex-column">
                        <span class="fs-5 fw-semibold">{{ cart_item.item.name }}</span>
                        <span class="text-success">{{ "%.2f" % (cart_item.item.price * cart_item.quantity) }}€</span>
                    </div>
                    <div class="item-quantity input-group">
                        <div class="d-flex align-items-center justify-content-center px-3 bg-dark text-white rounded-start">{{ cart_item.quantity }}</div>
                        <a href="{{ url_for('cart.decrement_item_quantity', restaurant_id=attributes.restaurant.id, cart_id=attributes.cart.id, item_id=cart_item.item.id) }}" class="btn btn-outline-dark" type="button">-</a>
                        <a href="{{ url_for('cart.increment_item_quantity', restaurant_id=attributes.restaurant.id, cart_id=attributes.cart.id, item_id=cart_item.item.id) }}" class="btn btn-outline-dark" type="button">+</a>
                    </div>
                </li>
            {% else %}
                <li class="list-group-item">
                    Your cart is so empty, it’s starting to question its existence—let’s fix that!
                </li>
            {% endfor %}
        </ul>

        <hr />

        {% if attributes.cart_items|length > 0 %}
            <div class="d-flex align-items-center justify-content-between">
                <p>Total</p>
                <span class="text-success">{{ attributes.total_price }}€</span>
            </div>
        {% endif %}
    </div>

    <div class="justify-self-end">
        <form method="POST">
            {{ attributes.place_order_form.hidden_tag() }}
            {{ attributes.place_order_form.wishes_text.label(class="form-label", for="wishes_text") }}
            {{ attributes.place_order_form.wishes_text(id="wishes_text", class="form-control") }}

            <div class="d-grid mt-3">
                <button type="submit" class="btn btn-dark">
                    <i class="fa-solid fa-credit-card me-2"></i>Place Order
                </button>
            </div>
        </form>
    </div>
</section>